language: python
sudo: false

branches:
    only:
        - master

python:
  - 2.7
  - 3.5

# addons:
#   apt:
#     packages:
#       - libfftw3-dev

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - ls
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  #  - sudo rm -rf /dev/shm
  #- sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose
  - python setup.py install
  - pip install codecov

# Use if anything needs to be done before tests are run
# before_script:
#     cd test
script:
    - nosetests --verbosity=3 --with-coverage --cover-package=aotools test/

after_success:
  - codecov
