language: python
sudo: false
branches:
  only:
  - master
python:
- 2.7
- 3.5

addons:
  apt:
    packages:
    - pandoc

before_install:
- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b
- export PATH=/home/travis/miniconda3/bin:$PATH
- ls
- conda update --yes conda
install:
- conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose matplotlib
- python setup.py install
- pip install codecov pypandoc
script:
- nosetests --verbosity=3 --with-coverage --cover-package=aotools test/
after_success:
- codecov

deploy:
  provider: pypi
  user: "andrewpaulreeves"
  skip_upload_docs: true
  password:
    secure: IQ76vBuc4JgL/CGwCm5tQT0v+tBbv8whGilTlfPAZ5iFwJz7J2YOsjRq0Zg2emsEneoJa59s9Lb9/JM3mzE02Dny87NPcKyiDNbVUwVasweMyxnhwg+UQFZA4xSYJ6Jval3OeelWZzB4hm5Vu117eIkQVr+iZrBrNf8nRUPTKUK2G749ex1l01+4Sjg/EAjzI3uXGX78MhZK5gN0MBb0JBvzzMcmhB898uQSIQ0XPXKugNQdt2qWrfa0GadO6Kbsov5XqeOcv7uuX9rmvjp/ViVWWqXbFBbhXgOFm40WQwbgqbO1DpBmF8BbYBt889/Iymyz/kPh/by7DD657/OctuMpi3PEqspPYj9fH4ZV5+kGs8Rv9XG3VM7T8k4ZjQW3BBTs7tEnKjVGZxop/RyX5qUNYy3aph272jwRHt3Gm1s+1zthWYsMqMiosDagDL9Qd1a1mT0ONPYuifbjE0somdsNTsp746vIkweE7y1Ni0BWuGqdH+EQSCnRURn5z+GUArL2pFxECnB4S45W1DI/CY8RIn9qI9RGFhSePlnLrYBAcAPhJRAcUNsWGJEuFCY5WM3XEENPwNUPNCxxdNwlvNXd5GXVSvcXswaD+LhluHhj12AOfttSgcdvsoO9+sWff0+5Zx2XdrVDcdEV4F5FzbZh1uN4q9CirTy+CQUyDb8=
